"""taskflow_meetings_roles_board_members

Revision ID: 99cb76befa8a
Revises: a9064b7934a1
Create Date: 2026-03-21 11:22:38.938090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99cb76befa8a'
down_revision: Union[str, Sequence[str], None] = 'a9064b7934a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'live', 'ended', 'tasks_proposed', 'reviewed', 'completed', name='meetingstatus', native_enum=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('board_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'user_id', name='uq_board_member')
    )
    op.create_index(op.f('ix_board_members_id'), 'board_members', ['id'], unique=False)
    op.create_table('meeting_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_files_id'), 'meeting_files', ['id'], unique=False)
    op.create_table('meeting_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_notes_id'), 'meeting_notes', ['id'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_participant')
    )
    op.create_index(op.f('ix_meeting_participants_id'), 'meeting_participants', ['id'], unique=False)
    op.create_table('meeting_task_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'dismissed', name='taskproposalstatus', native_enum=False), nullable=False),
    sa.Column('target_board_id', sa.Integer(), nullable=True),
    sa.Column('target_list_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['target_list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_task_proposals_id'), 'meeting_task_proposals', ['id'], unique=False)
    op.add_column('cards', sa.Column('meeting_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('cards_ibfk_2'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'meetings', ['meeting_id'], ['id'])
    op.create_foreign_key(None, 'cards', 'lists', ['list_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lists_ibfk_1'), 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('reports_to_id', sa.Integer(), nullable=True))
    # MySQL ENUM -> VARCHAR; map legacy roles before app expects hierarchy
    op.alter_column(
        "users",
        "role",
        existing_type=mysql.ENUM("admin", "member", collation="utf8mb4_unicode_ci"),
        type_=sa.String(length=32),
        nullable=True,
    )
    op.execute("UPDATE users SET role = 'director' WHERE role = 'admin'")
    op.execute("UPDATE users SET role = 'staff' WHERE role = 'member'")
    op.execute(
        "UPDATE users SET role = 'staff' WHERE role IS NULL OR role NOT IN "
        "('director','vp','gm','manager','staff')"
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.String(length=32),
        type_=sa.String(length=32),
        nullable=False,
    )
    op.create_foreign_key(None, 'users', 'users', ['reports_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('director', 'vp', 'gm', 'manager', 'staff', name='roleenum', native_enum=False),
               type_=mysql.ENUM('admin', 'member', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_column('users', 'reports_to_id')
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key(op.f('lists_ibfk_1'), 'lists', 'boards', ['board_id'], ['id'])
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_ibfk_2'), 'cards', 'lists', ['list_id'], ['id'])
    op.drop_column('cards', 'meeting_id')
    op.drop_index(op.f('ix_meeting_task_proposals_id'), table_name='meeting_task_proposals')
    op.drop_table('meeting_task_proposals')
    op.drop_index(op.f('ix_meeting_participants_id'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_meeting_notes_id'), table_name='meeting_notes')
    op.drop_table('meeting_notes')
    op.drop_index(op.f('ix_meeting_files_id'), table_name='meeting_files')
    op.drop_table('meeting_files')
    op.drop_index(op.f('ix_board_members_id'), table_name='board_members')
    op.drop_table('board_members')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
